modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/chromonym/chronoception/issues"
license = "BSD-3-Clause"

[[mods]]
modId = "chronoception"
version = "${version}"
displayName = "Chronoception"
authors = "chromonym"
description = '''
A Minecraft mod about perception of time (made for ModFest 1.21)
'''
logoFile = "chronoceptionicon.png"
displayURL = "https://modrinth.com/mod/chronoception"

[[dependencies.chronoception]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chronoception]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chronoception]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "chronoception.mixins.json"
